export const GAME_PERSPECTIVES = [
  "Cenital",
  "Isométrica",
  "Lateral",
  "Primera persona",
  "Tercera persona",
] as const;

export const GAME_THEMES = [
  "4X",
  "Acción",
  "Amor",
  "Ciencia ficción",
  "Comedia",
  "Drama",
  "Educación",
  "Fantasía",
  "Fiesta",
  "Guerra",
  "Historia",
  "Misterio",
  "Mundo abierto",
  "Negocios",
  "Niños",
  "No ficción",
  "Sandbox",
  "Sigilo",
  "Supervivencia",
  "Suspense",
  "Terror",
] as const;

export const GAME_GENRES = [
  "Aventura",
  "Beat 'em up",
  "Breakout",
  "Conducción",
  "Concurso",
  "Deporte",
  "Disparos",
  "Estrategia",
  "Hack and Slash",
  "Indie",
  "Juego de mesa",
  "Laberinto",
  "Lucha",
  "MOBA",
  "Musical",
  "Novela visual",
  "Pinball",
  "Plataformas",
  "Point-and-click",
  "Puzles",
  "Rol",
  "Simulación",
  "Táctica",
] as const;

export const GAME_TAXONOMY = {
  genres: GAME_GENRES,
  themes: GAME_THEMES,
  perspectives: GAME_PERSPECTIVES,
} as const;
